# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=250)),
                ('doctor', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BookAnAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=250)),
                ('doctor', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('file_number', models.CharField(max_length=20)),
                ('appointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointments')),
            ],
        ),
    ]
