# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-13 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='BookAnAppointment',
            new_name='BookAppointment',
        ),
    ]
