# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-13 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20181013_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_logo',
            field=models.CharField(default=datetime.datetime(2018, 10, 13, 20, 38, 36, 349543, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
