# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-13 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20181013_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_logo',
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='doctor_logo',
            field=models.CharField(default=datetime.datetime(2018, 10, 13, 20, 39, 58, 170019, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
