# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-25 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_auto_20181025_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='doctor',
            new_name='doctor_name',
        ),
    ]
